remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: YARA Forge
description: Streamlined YARA Rule Integration
show_downloads: true
google_analytics: G-5E91C4P04Y
github:
  core: https://github.com/YARAHQ/yara-forge/releases/latest/download/yara-forge-rules-core.zip
  extended: https://github.com/YARAHQ/yara-forge/releases/latest/download/yara-forge-rules-extended.zip
  full: https://github.com/YARAHQ/yara-forge/releases/latest/download/yara-forge-rules-full.zip
logo: /assets/images/yara-forge-logo.png